version: 0.0

os: linux

files:
  - source: ./src
    destination: /home/ubuntu/app
  - source: ./cloudwatch
    destination: /home/ubuntu/cloudwatch
  - source: ./src/webapp/dp_ng.conf
    destination: /etc/nginx/sites-available/

hooks:
  ApplicationStop:
    - location: ./codedeploy/app_stop.sh
      timeout: 120
      runas: ubuntu

  BeforeInstall:
    - location: ./codedeploy/b4_install.sh
      timeout: 120
      runas: ubuntu

  AfterInstall:
    - location: ./codedeploy/af_install.sh
      timeout: 120
      runas: ubuntu

  ApplicationStart:
    - location: ./codedeploy/app_start.sh
      timeout: 600
      runas: ubuntu
