version: 0.0

os: linux

files:
  - source: ./src
    destination: /home/ubuntu/app

hooks:
  ApplicationStop:
    - location: ./codedeploy/app_stop.sh
      timeout: 100
      runas: root

  BeforeInstall:
    - location: ./codedeploy/b4_install.sh
      timeout: 100
      runas: root

  ApplicationStart:
    - location: ./codedeploy/app_start.sh
      timeout: 600
      runas: root
