# Generated by Django 3.1.1 on 2020-10-07 13:25

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4,
                                                 editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4,
                                                 editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('updated_timestamp', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('question_text', models.TextField()),
                ('categories', models.ManyToManyField(blank=True,
                                                      related_name='questions', to='question_n_answer.Category')),
                ('user', models.ForeignKey(editable=False, null=True,
                                           on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4,
                                               editable=False, primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='answers',
                    to='question_n_answer.question')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
