# Generated by Django 3.1.1 on 2020-10-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_n_answer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('_id', models.UUIDField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('s3_object_name', models.CharField(max_length=200)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('Question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='question_n_answer.question')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='question_n_answer.answer')),
            ],
        ),
    ]
