# Generated by Django 3.1.1 on 2020-10-21 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('question_n_answer', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
