# Generated by Django 3.1.1 on 2020-10-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_n_answer', '0003_auto_20201021_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='_id',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='Question',
            new_name='question',
        ),
    ]
