# Generated by Django 3.1.1 on 2020-11-03 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_n_answer', '0005_auto_20201021_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='question_n_answer.answer'),
        ),
        migrations.AlterField(
            model_name='file',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='question_n_answer.question'),
        ),
    ]
